{% set name = "locache" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/locache-{{ version }}.tar.gz
  sha256: f1ef6b3e22dafe6dda95d82b45a750386735f01b2ec4df1859ffef52ac866c69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
  run:
    - python >={{ python_min }}

test:
  imports:
    - locache
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jla-gardner/locache
  summary: Cache expensive function calls to disk.
  license: MIT
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - awvwgk
